# Generated by Django 5.2.8 on 2025-12-28 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0002_alter_task_category_alter_task_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('work', 'Work'), ('school', 'School'), ('business', 'Business'), ('personal', 'Personal'), ('recreational', 'Recreational')], default='work', max_length=100),
        ),
    ]
